# easy_admin:
#   # config/packages/easy_admin.yaml
#   dashboard:
#     # Configuration du tableau de bord
#     role: "ROLE_ADMIN"
easy_admin:
    entities:
        Post:
            class: App\Entity\Post
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'content', type: 'fos_ckeditor' }
