easy_admin:
  design:
    brand_color: "#3498db" # Replace with your desired brand color
  entities:
    Post:
      class: App\Entity\Post
      form:
        fields:
          - { property: "title" }
          - { property: "content", type: "fos_ckeditor" }
