fos_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: full # Utilisation de la barre d'outils complète
            uiColor: "#000000" # Couleur de l'interface
            extraPlugins: "autogrow" # Plugin autogrow pour ajuster la hauteur
            autogrow_maxHeight: 800 # Hauteur maximale de l'éditeur
            removeButtons: 'Subscript,Superscript' # Retirer certains boutons inutiles


twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
